### ISSUE TITLE
Despawning Dinos

### ISSUE THREAD

**Issue by MintyNin** [Interactive-Modding/Jurassic-Reborn#77]
Hey there!

This is a hard issue to show using screenshots as there is no indicator other than the dinos suddenly being gone.

When playing, Dinos will randomly despawn or disappear from their enclosures. Even dinos with nametags/tamed dinosaurs will despawn, with no message in chat to show their death nor do they leave behind any drops.

This tends to happen when I leave the dinos.

Am I doing something wrong?

**Comment by Darth-Vitiate** [comment]
Hello! Did this occur on single-player or a multiplayer world?
